#!/bin/bash

rm -rf build/* || true
mkdir -p build/holostreetsLaTeX
cp -r example/* build
cp -r definitions build/holostreetsLaTeX
cp -r background build/holostreetsLaTeX
cp -r *.tex build/holostreetsLaTeX
cp -r shadowrun.cls build
cp LICENCE build/holostreetsLaTeX
cp -r images build/holostreetsLaTeX

sed -i 's/\\newcommand\\@inputprefix\[1\]{#1}/\\newcommand\\@inputprefix[1]{holostreetsLaTeX\/#1}/g' \
    build/shadowrun.cls
sed -i '1s/^/%\n/' build/shadowrun.cls
sed -i '1s/^/%\n/' build/shadowrun.cls
sed -i '1s/^/%\n/' build/shadowrun.cls
sed -i '1s/^/% !!! DO NOT EDIT THIS FILE !!!\n/' build/shadowrun.cls
sed -i '1s/^/%\n/' build/shadowrun.cls
sed -i '1s/^/% https:\/\/github.com\/TrueLunacy\/HolostreetsLatex\n/' build/shadowrun.cls
sed -i '1s/^/% If you do know what you are doing, contributions are welcome at\n/' build/shadowrun.cls
sed -i '1s/^/%\n/' build/shadowrun.cls
sed -i '1s/^/% the class works directly, you do not need to edit this file.\n/' build/shadowrun.cls
sed -i '1s/^/% Unless you know what you are doing, and you want to change the way\n/' build/shadowrun.cls
sed -i '1s/^/% It must be present here so Overleaf will build properly.\n/' build/shadowrun.cls
sed -i '1s/^/% This is an internal file for the Shadowrun layout.\n/' build/shadowrun.cls
sed -i '1s/^/%\n/' build/shadowrun.cls
sed -i '1s/^/% !!! DO NOT EDIT THIS FILE !!!\n/' build/shadowrun.cls
sed -i '1s/^/%\n/' build/shadowrun.cls
sed -i '1s/^/%\n/' build/shadowrun.cls
sed -i '1s/^/%\n/' build/shadowrun.cls

rm build/holostreetsLaTeX/images/*-debug.png
mogrify -resize '1200x1200>' build/holostreetsLaTeX/**/*.png

zip -r build/holostreetsLaTeX-overleaf.zip build/*